<?xml version="1.0" encoding="utf-8"?><Database Name="DoAnChuyenNganh" Class="DataDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=MSI\MSSQLSEVER2019;Initial Catalog=DoAnChuyenNganh;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DoAnChuyenNganhConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.DatPhong" Member="DatPhongs">
    <Type Name="DatPhong">
      <Column Name="madatPhong" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="makh" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="maPhong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="gia" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="mathanhtoan" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ngaydatPhong" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ngaytraPhong" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="TrangthaiThanhToan_DatPhong" Member="TrangthaiThanhToan" ThisKey="mathanhtoan" OtherKey="mathanhtoan" Type="TrangthaiThanhToan" IsForeignKey="true" />
      <Association Name="KhachHang_DatPhong" Member="KhachHang" ThisKey="makh" OtherKey="makh" Type="KhachHang" IsForeignKey="true" />
      <Association Name="Phong_DatPhong" Member="Phong" ThisKey="maPhong" OtherKey="maPhong" Type="Phong" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TrangthaiThanhToan" Member="TrangthaiThanhToans">
    <Type Name="TrangthaiThanhToan">
      <Column Name="mathanhtoan" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="trangthai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="TrangthaiThanhToan_DatPhong" Member="DatPhongs" ThisKey="mathanhtoan" OtherKey="mathanhtoan" Type="DatPhong" />
    </Type>
  </Table>
  <Table Name="dbo.KhachHang" Member="KhachHangs">
    <Type Name="KhachHang">
      <Column Name="makh" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="hoten" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="diachi" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="dienthoai" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Association Name="KhachHang_DatPhong" Member="DatPhongs" ThisKey="makh" OtherKey="makh" Type="DatPhong" />
    </Type>
  </Table>
  <Table Name="dbo.LoaiPhong" Member="LoaiPhongs">
    <Type Name="LoaiPhong">
      <Column Name="maloaiPhong" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="tenloaiphong" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="LoaiPhong_Phong" Member="Phongs" ThisKey="maloaiPhong" OtherKey="maloaiPhong" Type="Phong" />
    </Type>
  </Table>
  <Table Name="dbo.Phong" Member="Phongs">
    <Type Name="Phong">
      <Column Name="maPhong" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="soPhong" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="giaPhong" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="maloaiPhong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="matrangthaiPhong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Phong_DatPhong" Member="DatPhongs" ThisKey="maPhong" OtherKey="maPhong" Type="DatPhong" />
      <Association Name="LoaiPhong_Phong" Member="LoaiPhong" ThisKey="maloaiPhong" OtherKey="maloaiPhong" Type="LoaiPhong" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Quyen" Member="Quyens">
    <Type Name="Quyen">
      <Column Name="maquyen" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="tenquyen" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Quyen_TaiKhoan" Member="TaiKhoans" ThisKey="maquyen" OtherKey="maquyen" Type="TaiKhoan" />
    </Type>
  </Table>
  <Table Name="dbo.TaiKhoan" Member="TaiKhoans">
    <Type Name="TaiKhoan">
      <Column Name="mataikhoan" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="hoten" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="matkhau" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="maquyen" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Quyen_TaiKhoan" Member="Quyen" ThisKey="maquyen" OtherKey="maquyen" Type="Quyen" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TrangThaiPhong" Member="TrangThaiPhongs">
    <Type Name="TrangThaiPhong">
      <Column Name="matrangthaiPhong" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="trangthai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>